.\" generated with Ronn/v0.5
.\" http://github.com/rtomayko/ronn/
.
.TH "ANTFARM\-PLUGINS" "1" "September 2010" "" "ANTFARM"
.
.SH "NAME"
\fBantfarm\-plugins\fR \-\- plugins for the ANTFARM passive network mapping tool
.
.SH "DESCRIPTION"
ANTFARM (Advanced Network Toolkit For Assessments and Remote Mapping) is a
passive network mapping application that utilizes output from existing network
examination tools to populate its OSI\-modeled database. This data can then be
used to form a ‘picture’ of the network being analyzed.
.
.P
ANTFARM plugins provide an easy way to extend the parsing and outputting of
data into and out of ANTFARM. Currently available plugins are described below.
.
.SH "PLUGINS"
load\-host:
.
.P
Given a file that contains a list of IP addresses, one per line, this plugin
simply creates an IpInterface model for each address provided.
.
.TP
\fB\-\-input\-file\fR \fIfile\fR
The location of the file containing the IP addresses
.
.P
load\-network:
.
.P
Given a file that contains a list of IP networks, one per line, this plugin
simply creates and IpNetwork model for each network address provided.
.
.TP
\fB\-\-input\-file\fR \fIfile\fR
The location of the file containing the IP network addresses
.
.SH "COPYRIGHT"
Copyright (2008\-2010) Sandia Corporation. Under the terms of Contract
DE\-AC04\-94AL85000 with Sandia Corporation, the U.S. Government retains certain
rights in this software.
.
.P
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, distribute with modifications,
sublicense, and/or sell copies of the Software, and to permit persons to whom
the Software is furnished to do so, subject to the following conditions:
.
.P
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
.
.P
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.
.P
Except as contained in this notice, the name(s) of the above copyright holders
shall not be used in advertising or otherwise to promote the sale, use or other
dealings in this Software without prior written authorization.
