.\" generated with Ronn/v0.5
.\" http://github.com/rtomayko/ronn/
.
.TH "ANTFARM\-PLUGINS" "1" "June 2010" "" ""
.
.SH "NAME"
\fBantfarm\-plugins\fR \-\- plugins for the ANTFARM passive network mapping tool
.
.SH "DESCRIPTION"
ANTFARM (Advanced Network Toolkit For Assessments and Remote Mapping) is a
passive network mapping application that utilizes output from existing network
examination tools to populate its OSI\-modeled database. This data can then be
used to form a ‘picture’ of the network being analyzed.
.
.P
ANTFARM plugins provide an easy way to extend the parsing and outputting of
data into and out of ANTFARM. Currently available plugins are described below.
.
.SH "PLUGINS"
load\-host:
.
.P
Given a file that contains a list of IP addresses, one per line, this plugin
simply creates an IpInterface model for each address provided.
.
.TP
\fB\-\-input\-file\fR \fIfile\fR
The location of the file containing the IP addresses
.
.P
load\-network:
.
.P
Given a file that contains a list of IP networks, one per line, this plugin
simply creates and IpNetwork model for each network address provided.
.
.TP
\fB\-\-input\-file\fR \fIfile\fR
The location of the file containing the IP network addresses
.
.SH "COPYRIGHT"
Copyright (2008\-2010) Sandia Corporation. Under the terms of Contract
DE\-AC04\-94AL85000 with Sandia Corporation, the U.S. Government retains certain
rights in this software.
.
.P
This library is free software; you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation; either version 2.1 of the License, or (at your option) any
later version.
.
.P
This library is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
.
.P
You should have received a copy of the GNU Lesser General Public License along
with this library; if not, write to the Free Software Foundation, Inc., 59
Temple Place, Suite 330, Boston, MA 02111\-1307 USA.
