require 'data_objects'
require 'do_sqlite3'

require 'dm-constraints'
require 'dm-validations'

# require all the models
require 'antfarm/models/ethernet_interface'
require 'antfarm/models/ip_interface'
require 'antfarm/models/ip_network'
require 'antfarm/models/layer_two_interface'
require 'antfarm/models/layer_three_interface'
require 'antfarm/models/layer_three_network'
require 'antfarm/models/node'
# require 'antfarm/models/private_network'
# require 'antfarm/models/traffic'
# require 'antfarm/models/dns_entry'
# require 'antfarm/models/action'
# require 'antfarm/models/service'
# require 'antfarm/models/operating_system'
